### ISSUE TITLE
blocked I2C bus

### ISSUE THREAD

**Issue by Memoryfault** [paulvha/SN-GCJA5_on_raspberry#1]
gcja5 does not releases bus. Other devices on bus became unavailable. Nevertheless SN-GCJA5 still can be polled. To see run i2cdetect -y 1 before and after gcja5.

**Comment by paulvha** [comment]
I see what you mean. The issue is because I am using BCM2835 library. I do not use the /dev/i2c-1 kernel code. When the program is exiting in I2C_close() I perform a bcm2835_i2c_end() call. This will reset the GPIO 5 and 3 as input instead of SDA and SCL. 
The quick workaround for you would be to comment out the bcm2835_i2c_end() call (around line 400 in gcja5_lib.cpp)
 
I am actually working on an extension that will include the option to use /dev/i2c-1, next to BME2835. I will now also include a command line option to prevent resetting the pins to input.

regards,
Paul
