### ISSUE TITLE
Unexpected very high values

### ISSUE THREAD

**Issue by rsnape** [paulvha/SN-GCJA5_on_raspberry#2]
Hi,
apologies for raising as an issue, this is more of a question but thought this might be a way to ask for insight.

I notice [here](https://github.com/paulvha/SN-GCJA5_on_raspberry/blob/master/gcja5.cpp#L412) you reference an issue with high values 

I have observed the same thing with the SNGCJA5 although in my case when using python code (also using bcm2835 on raspberry pi).  I wondered if you had any further info on why this happens?  You reference the device being out of sync in the comments, but I'm not sure what that means and thought you might be able to enlighten me.

**Comment by paulvha** [comment]
hi
As I was not impressed by the sensor I have not spend a lot of time since after the posting on the sensor. The firmware on the SNGCJ5 was having a number of issues as documented in the ODT-document in the extras folder. And the right firmware makes the difference. 

Brainstorming on reasons:  

- It could be that the values in the SNGCJ5 are updated while being read (either serial or I2C), maybe like shifting bit a shift register from left to right. 

- Could be a power issue that it is performing a measurement at the time of reading and the laser takes power impacting the communication logic (have not tested with a scope on any power fluctuations).

- Could be SNGCJA5 internal timing (logic) within the sensor to provide the correct bits on time. E.g. performing a measurement and/or calculation, while performing communication at the same time.

- I would not expect the raspberry HW or SW to be an issue as I had the same issue on the MEGA2560.

Hope that helps and any insight from you could be of interest to me.

regards,
Paul

**Comment by rsnape** [comment]
Dear Paul,

Thank you for the reply.  The ODT document was really helpful as are your further comments above.  I've done some further work with the sensor and sadly haven't got any further insight, although I'm fairly confident that there is not a power issue unless it is within the sensor casing itself.

I suspect you may be right about this being either a timing issue or a failure to effectively lock out reading while a value is being shifted that is causing this anomaly.  I thought I had found a pattern at one point that high bytes were set to &FFFF, but even this was not consistent.

With that in mind, like you, I think I will write this sensor off and try to find another to suit my project.

Thanks again for the swift reply.

Regards,
Richard

**Comment by paulvha** [comment]
have a look at the SPS30... found that a good one for PM2.5, not so much PM10.. https://github.com/paulvha/sps30
